# Generated by Django 3.1.5 on 2021-01-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210130_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='h.jpg', upload_to='profile_pics'),
        ),
    ]
